### ISSUE TITLE
exception 'Omeka_Plugin_Exception' 

### ISSUE THREAD

**Issue by AngeloVenera** [kent-state-university-libraries/ElementAdministration#1]
Hi at all

during the installation of this pulgin i have this error:

2016-05-06T07:09:00+00:00 ERR (3): exception 'Omeka_Plugin_Exception' with message 'Hook callback "hookBeforeSaveItem" does not exist.' in /var/www/html/omeka/application/libraries/Omeka/Plugin/AbstractPlugin.php:162
Stack trace:
#0 /var/www/html/omeka/application/libraries/Omeka/Plugin/AbstractPlugin.php(106): Omeka_Plugin_AbstractPlugin->_addHooks()
#1 /var/www/html/omeka/application/libraries/Omeka/Plugin/Loader.php(380): Omeka_Plugin_AbstractPlugin->setUp()
#2 /var/www/html/omeka/application/libraries/Omeka/Plugin/Loader.php(217): Omeka_Plugin_Loader->_loadPluginBootstrap(Object(Plugin))
#3 /var/www/html/omeka/application/libraries/Omeka/Plugin/Installer.php(126): Omeka_Plugin_Loader->load(Object(Plugin), true)
#4 /var/www/html/omeka/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#5 /var/www/html/omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#6 /var/www/html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#7 /var/www/html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#9 /var/www/html/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#10 /var/www/html/omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#11 /var/www/html/omeka/admin/index.php(28): Omeka_Application->run()
#12 {main}

Thank you

**Comment by joecorall** [comment]
Hello,

Thank you for trying out the plugin! This issue should be resolved if you pull down the latest changes.

I should also note: this plugin hasn't had an official release yet, so there more than likely are still some bugs here-and-there.

Joe
